logging: 
  level: 
    root: WARN
  file: logfile.log
  
spring: 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dbjruiznavarrorecetario

encryptor: 
  key: Samanid?269RuKl.
  vector: onEmoP.TrcE?sfrs
  jwt:
    secret: b5d12534214r21321425u12435tp234r